language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
env: FC='gfortran-5'
install:
  - bash install_njoy.sh
script:
  - bash util/run_njoy.sh 26-Fe-56g.jeff33
