language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
before_script:
  - FC=gfortran-5 cmake .
  - make
install:
  - bash install_njoy.sh
