language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-5
      - xsltproc
env:
  global:
    - FC='gfortran-5'
install:
  - git clone https://github.com/luca-fiorito-11/PVBV_utils.git
  - bash ${TRAVIS_BUILD_DIR}/PVBV_utils/install_njoy.sh
script:
  - bash ${TRAVIS_BUILD_DIR}/PVBV_utils/run_njoy.sh 26-Fe-56g.jeff33
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - echo "<messages>" > ${TRAVIS_BUILD_DIR}/data.xml
  - bash ${TRAVIS_BUILD_DIR}/PVBV_utils/parse_njoy_messages.sh ${TRAVIS_BUILD_DIR}/output >> ${TRAVIS_BUILD_DIR}/data.xml
  - echo "<messages>" >> ${TRAVIS_BUILD_DIR}/data.xml
  - bash ${TRAVIS_BUILD_DIR}/PVBV_utils/make_html.sh ${TRAVIS_BUILD_DIR}/data.xml
deploy:
  - provider: releases
    api-key: $GITHUB_TOKEN
    file: "tape51"
    skip_cleanup: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: html
    overwrite: yes
    on:
      branch: master
