language: generic
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
env:
  global:
    - FC='gfortran-5'
    - NJOY='${HOME}/NJOY2016/bin/njoy'
install:
  - bash install_njoy.sh
script:
  - bash util/run_njoy.sh 26-Fe-56g.jeff33
