language: generic
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-5
#      - g++-5
#      - gfortran-5
addons:
  apt:
    packages: xsltproc
env:
  global:
    - FC='gfortran-5'
#install:
#  - bash install_njoy.sh
#script:
#  - bash util/run_njoy.sh 26-Fe-56g.jeff33
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - mkdir -p ${TRAVIS_BUILD_DIR}/html
  - echo "<!DOCTYPE html>" > ${TRAVIS_BUILD_DIR}/html/index.html
  - xsltproc transform.xsl output.xml >> ${TRAVIS_BUILD_DIR}/html/index.html
  - echo 'theme: jekyll-theme-cayman' > ${TRAVIS_BUILD_DIR}/html/_config.yml
deploy:
#  api-key: $GITHUB_TOKEN
#  provider: releases
#  file: "tape30"
#  skip_cleanup: true
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: html
  overwrite: yes
  on:
    branch: master
