language: generic
env:
  - FILENAME=26-Fe-56g.jeff33
branches:
  only: master
jobs:
  include:
    - stage: test
      name: utils
      install:
        - curl -O "https://www-nds.iaea.org/public/endf/utility/bin/fizcon-linux-64"
        - chmod 777 fizcon-linux-64
      script:
        - echo -e "$FILENAME\nFIZCON.OUT\n\nDONE" |./fizcon-linux-64
    - stage: test
      name: utils
      install:
        - curl -O "https://www-nds.iaea.org/public/endf/utility/bin/checkr-linux-64"
        - chmod 777 checkr-linux-64
      script:
        - echo -e "$FILENAME\nCHECKR.OUT\n\nDONE" | ./checkr-linux-64
    - stage: utils
      name: psyche
      install:
        - curl -O "https://www-nds.iaea.org/public/endf/utility/bin/psyche-linux-64"
        - chmod 777 psyche-linux-64
      script:
        - echo -e "$FILENAME\nPSYCHE.OUT\n\nDONE" | ./psyche-linux-64
    - stage: njoy
      name: njoy
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gfortran-5
          - xsltproc
        env:
          - FC='gfortran-5'
      install:
        - git clone https://github.com/luca-fiorito-11/PVBV_utils.git
        - bash ${TRAVIS_BUILD_DIR}/PVBV_utils/install_njoy.sh
      script:
        - bash PVBV_utils/run_njoy.sh $FILENAME
        - mkdir -p html
        - xsltproc transform.xsl <( PVBV_utils/parse_njoy_messages.sh output ) | sed '1d;$d' > html/index.xml
        - "echo 'theme: jekyll-theme-cayman' > html/_config.yml"
      before_deploy:
        - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
      deploy:
        - provider: releases
          api-key: $GITHUB_TOKEN
          file: "tape51"
          skip_cleanup: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: false
          local-dir: html
          overwrite: yes
          on:
            branch: master
