language: generic
env:
  global:
    - FILENAME=26-Fe-56g.jeff33
branches:
  only: master
jobs:
  include:
    - stage: aaa
      name: inter
      before_install:
        - curl --verbose -O "https://github.com/luca-fiorito-11/Fe56_test/releases/download/20181029-f401a3f-Luca-Fiorito/26-Fe-56g.jeff33.pendf"
      install:
        - curl --verbose -O "https://www-nds.iaea.org/public/endf/utility/bin/inter-linux-64"
        - chmod 777 inter-linux-64
      script:
        - ls
        - cat ${FILENAME}.pendf | wc -l
        - ./inter-linux-64 ${FILENAME}.pendf
    - stage: utils
      name: fizcon
      install:
        - curl -O "https://www-nds.iaea.org/public/endf/utility/bin/fizcon-linux-64"
        - chmod 777 fizcon-linux-64
      script:
        - echo -e "$FILENAME\nFIZCON.OUT\n\nDONE" |./fizcon-linux-64
    - stage: utils
      name: checkr
      install:
        - curl -O "https://www-nds.iaea.org/public/endf/utility/bin/checkr-linux-64"
        - chmod 777 checkr-linux-64
      script:
        - echo -e "$FILENAME\nCHECKR.OUT\n\nDONE" | ./checkr-linux-64
    - stage: utils
      name: psyche
      install:
        - curl -O "https://www-nds.iaea.org/public/endf/utility/bin/psyche-linux-64"
        - chmod 777 psyche-linux-64
      script:
        - echo -e "$FILENAME\nPSYCHE.OUT\n\nDONE" | ./psyche-linux-64
    - stage: njoy
      name: njoy
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gfortran-5
            - xsltproc
      env:
        - FC='gfortran-5'
        - NJOY_TOLER=0.1   # Reconstruction tolerance
        - NJOY_TEMP=293.6  # Processing temperature (K)
        - NJOY_EMAX=10     # Maximum energy for thermal treatment (eV)
        - NJOY_ACE_SUFF=03 # ACE file suffix
      install:
        - git clone https://github.com/luca-fiorito-11/PVBV_utils.git
        - bash ${TRAVIS_BUILD_DIR}/PVBV_utils/install_njoy.sh
      script:
        - bash PVBV_utils/run_njoy.sh $FILENAME
        - mkdir -p html
        - xsltproc PVBV_utils/transform.xsl <( PVBV_utils/parse_njoy_messages.sh output ) | sed '1d;$d' > html/index.html
        - "echo 'theme: jekyll-theme-cayman' > html/_config.yml"
      after_success:
        - git tag "$(date +'%Y%m%d')-$(git log --format=%h -1)-$(git log --format=%an -1 | tr " " "-")"
      deploy:
        - provider: releases
          api-key: $GITHUB_TOKEN
          file:
            - ${FILENAME}.ace 
            - ${FILENAME}.pendf 
          skip_cleanup: true
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: html
          overwrite: yes
          on:
            branch: master
    - stage: inter
      name: inter
      before_install:
        - TAG="$(date +'%Y%m%d')-$(date +'%H%M')-$(git log --format=%h -1)-$(git log --format=%an -1 | tr " " "-")"
        - REMOTE_URL=$(url=$(git ls-remote --get-url);echo ${url%.*})
        - curl --verbose -O "${REMOTE_URL}/releases/download/${TAG}/${FILENAME}.pendf"
      install:
        - curl --verbose -O "https://www-nds.iaea.org/public/endf/utility/bin/inter-linux-64"
        - chmod 777 inter-linux-64
      script:
        - echo -e "26-Fe-56g.jeff33.pendf\nINTER.OUT\n\nDONE" | ./inter-linux-64
